const collections = {
  accounts: {
    logs: "v2logs",
    otps: "v2otps",
    users: "v2users",
    roles: "v2roles",
    staffs: "v2staffs",
    department: "v2department",
    supplier: "v2supplier",
    passwordChange: "v2account-password-change",
  },
  support: {
    emails: "v2emails",
    messages: "v2messages",
    complaints: "v2complaints",
    complaintCategories: "v2complaint-categories",
    complaintResponses: "v2complaint-responses",
  },
  notifications: "v2notifications",
  feedbacks: "v2feedbacks",
  wallet: {
    base: "v2wallets",
    histories: "v2wallet-histories",
    withdrawals: "v2withdrawals",
    transactions: "v2transactions",
    paymentLinks: "v2payment-links",
    banking: "v2banking-informations",
  },
  icart: {
    icarts: "v2icarts",
    invoices: "v2invoices",
    preorder: "v2icart-subscriptions-preorder",
    concepts: "v2concepts",
    conceptFee: "v2concept-activation-fee",
    conceptMenu: "v2concept-menu",
    conceptExtra: "v2concept-extra",
    conceptIngredients: "v2concept-ingredients",
    conceptMachineries: "v2concept-machineries",
    brands: "v2icart-brands",
    outlets: "v2icart-outlets",
    locations: "v2locations",
    purchases: "v2icart-purchases",
    subscriptions: "v2icart-subscriptions",
    bills: "v2subscription-bills",
    securityDeposit: "v2security-deposits",
    sales: "v2icart-sales",
    orders: "v2icart-orders",
    customers: "v2icart-customers",
    locationChange: "v2location-change",
    brandChange: "v2brand-change",
    conceptChange: "v2concept-change",
  },
  config: {
    cities: "v2operating-cities",
    settings: "v2operating-settings",
    countries: "v2operating-countries",
    paymentChannels: "v2operating-payment-channels",
  },
  inventory: {
    categories: "v2material-categories",
    material: "v2materials",
    materialRequest: "v2material-requests",
    materialRequestItems: "v2material-request-items",
    supplyRequest: "v2supply-requests",
    supplyRequestItems: "v2supply-request-items",
    supplyRequestResponses: "v2supply-request-responses",
    products: "v2inventory-products",
    prices: "v2inventory-prices",
    productsHistory: "v2inventory-products-history",
    mixture: "v2inventory-mixture",
    supplies: "v2inventory-supplies",
  },
  admin: {
    accounts: "v2admin-accounts",
  },
};

export default collections;
